language: r

warnings_are_errors: true

r_check_args: --as-cran 

sudo: required

before_install:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install mesa-common-dev freeglut3 freeglut3-dev libglew1.5 libglew1.5-dev libglu1-mesa libglu1-mesa-dev libgl1-mesa-glx libgl1-mesa-dev; fi

jobs:
  include:
    - os: linux
      r: devel
      env:
        - _R_SAN_=TRUE 
        - _R_CHECK_FULL_=TRUE
        - RGL_USE_NULL=TRUE
        
    - os: linux
      r: devel
      addons:
        apt:
          packages:
            - valgrind
      r_check_args: --use-valgrind
      env:
        - _R_CHECK_FULL_=TRUE
        - _R_CHECK_USE_VALGRIND=TRUE
        - RGL_USE_NULL=TRUE

#jobs: RVERSION=devel _R_SAN_=TRUE _R_CHECK_FULL_=TRUE _R_CHECK_CRAN_INCOMING_=TRUE _R_CHECK_CRAN_INCOMING_REMOTE_=TRUE _R_CHECK_CRAN_INCOMING_USE_ASPELL_=TRUE _R_CHECK_FORCE_SUGGESTS_=TRUE
  
#env:
#  global: RGL_USE_NULL=TRUE

